#!/bin/bash

# Check if .env file exists
if [ ! -f .env ]; then
    # Copy .env.example to .env
    cp .env.example .env
    echo ".env file created from .env.example."
fi

# Ensure the logs directories exist
mkdir -p logs
cd logs
mkdir -p postgres
